services:
  app:
    image: todo-frontend-dev
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # this will simply tell which docker file to read
    volumes:
      - ./:/usr/src/app
    ports:
      - 5173:5173
    environment:
      - VITE_API_URL=http://localhost:3000
    container_name: todo-frontend-dev
