services:
  app:
    image: todo-frontend-prod
    build: 
      context: ./todo-frontend
      dockerfile: Dockerfile
    container_name: todo-frontend-prod
    environment:
      - VITE_BACKEND_URL=/api 

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
    restart: unless-stopped 

  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data
    restart: unless-stopped

  server:
    image: todo-backend-prod
    build:
      context: ./todo-backend  # This should point to the backend directory
      dockerfile: Dockerfile
    ports:
      - 3666:3000
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://root:example@mongo:27017/the_database?authSource=admin
    depends_on:
      - mongo
      - redis

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: td-reverse-proxy
    depends_on:
      - app
      - server