services:
  app:
    image: todo-frontend-dev #building the image outside of the frontend root
    build: 
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    volumes: 
      - ./todo-frontend:/usr/src/app
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: td-reverse-proxy
    depends_on:
      - app