services:
  app:
    image: phonebook-frontend-prod
    build: 
      context: ./phonebook-frontend
      dockerfile: Dockerfile
    container_name: phonebook-frontend-prod
  server:
    image: phonebook-backend-prod
    build: 
      context: ./phonebook-backend
      dockerfile: Dockerfile
    container_name: phonebook-backend-prod

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: phonebook-reverse-proxy
    depends_on:
      - app
      - server


